### ISSUE TITLE
Support Page -> getting started section navigation box needed to be aligned correctly.

### ISSUE THREAD

**Issue by vishnupsingh523** [princekumarcyber/Blood-Donation-#1]
![image](https://user-images.githubusercontent.com/49968961/111038509-65322500-844f-11eb-9896-75986f5be4fc.png)
In the given Image the navigation box of getting started section is not at the right place.

**Comment by princekumar-code** [comment]
If you would like to work with this issue then I can assign you

**Comment by vishnupsingh523** [comment]
Yeah I would love to work on this 😄 @DPrinceKumar  👍

**Comment by vishnupsingh523** [comment]
Hey @DPrinceKumar ,
I have done some changes to align it properly see if you like it 👍 

![image](https://user-images.githubusercontent.com/49968961/111074895-46916400-850b-11eb-9851-da1fd7552332.png)

**Comment by princekumar-code** [comment]
it great you can make PR

**Comment by vishnupsingh523** [comment]
Okay @DPrinceKumar ,
<a href="https://github.com/DPrinceKumar/Blood-Donation-/pull/2"> click here</a> to see the pull request. 👍
